### ISSUE TITLE
Matomo Analytics

### ISSUE THREAD

**Issue by dbranchini** [cul-it/wp-cul-main#25]

**Comment by manolobevia** [comment]
# DRAFT

## Matomo metric
Data gathered from Jan 1, 2019 to present for CUL website

`Note:` Matomo can't handle this data range often. I get performance issues, and the message below:

> "Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance"

Also, we should upgrade Matomo to latest version. I sent a ticket to CUL System Group asking if they can upgrade it.

> Warning
> Matomo will stop supporting PHP 7.0 in the next major version. Upgrade your PHP to at least PHP 7.2, before it's too late!
> The PHP version 7.0 you are using has reached its End of Life (EOL). You are strongly urged to upgrade to a current version, as using this version may expose you to security vulnerabilities and bugs that have been fixed in more recent versions of PHP.
> You must upgrade your PHP version in order to receive the latest Matomo update.
> Matomo cannot be upgraded to the latest major version because your PHP version is too old. Please upgrade your PHP version to at least PHP 7.2 so your Matomo analytics data stays secure.
> 

### Visitors
####  Overview
- We have ≈ 2,400,000 visits (equivalent to sessions in GA), with an average of 3 min and 11s per visit.
- 60% visits have bounced (left the website after one page)
- Users doesn't take too many actions on CUL site. 2.1 actions (page views, downloads, outlinks and internal site searches) per visit. Does people find what they need fast in about 2 clicks? Are users engage with the content provided?
- A total of 4,098,600 pageviews, 2,973,026 unique pageviews
- 944 total internal searches on website, 243 unique.  People are not searching internal content in CUL site. Do they find what they need without the use of the internal search form?
- We have 3,065 downloads, 2,722 unique downloads.
- 628,804 [outlinks](https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=range&date=2019-01-01,2021-09-13&segment=&category=General_Actions&subcategory=General_Outlinks) (expand newcatalog.library.cornell.edu), 534,539 unique outlinks. Of those outlinks **200k** goes to catalog from CUL site.

#### Visits log
I think it is worthy to spend time checking user logs and see how they are interacting with the site.
- [Sample 1](https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=range&date=2019-01-01,2021-09-12&segment=&category=General_Visitors&subcategory=Live_VisitorLog&popover=visitorProfile$3A7efe416a0609e41e) visitor profiles
- [Sample 2](https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=range&date=2019-01-01,2021-09-12&segment=&category=General_Visitors&subcategory=Live_VisitorLog&popover=visitorProfile$3Aa853de7479dcb8ee) visitor profiles
Some cases it doesn't make any sense. The sample 2 summary shows the following:
User spent a total of 8 days 14 hours on the website, and viewed 1284 pages in 54 visits. All the visits are to the cul homepage pretty much.

`Note`: Can we create an event to get the first 100 profiles with the most site usage?

#### Locations:
49% of our visits are fromn Ithaca, and 85% from USA.

####  Devices:
Generic Desktop	1,132,688 (48%)
Apple - Generic Desktop	938,423 (39%)
Very low mobile usage.

####  Operating System versions:
40% comes from Windows 10 (from public computing ?). About 30% from Mac OS and IOS, minimal Android use.


### Behavior

#### Pages 
From all visits, homepage has 60% of the visits (2.4 million pageviews) with an exit rate of 91%. Average time is 2 min 25 sec (5min with GA). Then Research (340k/ 8%) is the second most visited section, followed by services (253k/6%) about(197k/5%), and libraries(118k/3%).

#### Most visited pages within section
Research -> /citation
Services -> /request
About -> /news
Libraries -> /olin

#### Entry pages

Entrances (what are the pages users uses as the entry point to access CUL site)

- index	68%
- research	10.4%
- services	3.6%
- about	2.9%
- libraries	2.3

#### Exit rate

- homepage	91%
- /research	90% (so many external links... makes sense)
- /services	56%
- /about	54%
- /libraries	68%

#### Page Titles (most visited pages)

- Homepage 60%
- Research page 3.6%
- Research/Citation Management 3%
- Libraries and hours 2.5%
- Services 2.6%
- About Us 1.8%

#### Internal site search
Total of 764 searches.

####  Clicked outlinks
35% of the outlinks click goes to several pages to the catalog website from CUL site. 9.5% to owl.english.purdue.edu, and 9.1% to encompass.library.cornell.edu

Events created: How many times users click on the following links below, located in the homepage.

- Catalog 	65,865	
- Databases	62,861	
- Summon	   17,496	
- Ejournals	14,373	
- Images	1,996

#### Downloads
Probably staff is the biggest audience: Most downloaded content is CUL org Chart, Course reserves submission forms, Wiley journals, etc.
Are all these downloaded content (around 60 files) accessible (pdf, xlsx, doc)?

####  Visits per visit duration.
Of 1.6 millions of visits, users spend between 0-10 seconds. Of 131k visits, users spent on site 11-30s, and of 90k visits people spent 31-60s.

####  Visits by Visit Number
Visit number        visits           %visits
1 visit	            951,484	    40%
2 visits	            233,166	    10%
3 visits	             126,177	    5%
4 visits	              84,913	    4%
5 visits	             64,393	    3%

#### Transitions (equivalent to page flow in GA)
Pages with the most interaction:

- Homepage (2430362 pageviews)
- /research/citation (223356 pageviews)
- /libraries (134491 pageviews)
- /covid-19 (69993 pageviews)
- /myacctpage (59005 pageviews)
- /myacct (51406 pageviews)

[Matomo's transition page](https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=1#?idSite=1&period=range&date=2019-01-01,2021-09-12&segment=&category=General_Actions&subcategory=Transitions_Transitions)

### Acquisition:

#### Overview
55% of visits are direct entries, and 36% from search engines. [Check transitions page](https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=range&date=2019-01-01,2021-09-12&segment=&category=General_Actions&subcategory=Transitions_Transitions) (page flow in GA) for home.

#### All channels
Of a total of 2,365,765 visits, 838,707 (34%) come from search engines (no access to keywords due to privacy or cul private computing ip restriction). 1.6% from guides.library.cornell.edu, 0.5% from cornell.edu, and 0.3% from catalog. Users on catalog practically don't visit cul site.

#### Search Engines and Keywords
We have more than 800k unknown keywords from google search (primary search engine) to access CUL site.

####  Social network
53% of visits (3,100 visits) come from Facebook. Really low social network activity.

#### D&A Metric
Date from 2019 to Present.

**[Visitors Overview](https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=2#?idSite=2&period=range&date=2019-01-01,2020-12-31&segment=&category=General_Visitors&subcategory=General_Overview)**
1.13 millions visits.

**[Referrers](https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=2#?idSite=2&period=range&date=2019-01-01,2020-12-31&segment=&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll)**: We have proximally 200k visits from library website to the catalog of 2.4 million visits CUL site gets.

Catalog gets 1,13 million visits. From those visits, 680k are direct entries and 
438k from websites 51%, which 195k comes from library.cornell.edu. 

We have 1.8 million sessions just for CUL home. From CUL site we redirect people to catalog. We thought users use primarily CUL home to go to catalog, but we have only 195k referrals. Also we see cul home has 91% exit rate. They don't exit to go to catalog in huge proportions, users just leave cul homepage without doing any interactions.

We need to consider people searching the [catalog from other units](https://webstats.library.cornell.edu/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=2#?idSite=2&period=range&date=2019-01-01,2020-12-31&segment=&category=Referrers_Referrers&subcategory=Referrers_SubmenuWebsitesOnly) from other units. Does people search the catalog from unit sites?  Not too much, check the link above, 

There are 56k clicks from cul site to d&a homepage and those (I guess) are coming from catalog link on cul homepage (Catalog link has 65k clicks) not from search catalog form on CUL site.

How much users uses the search catalog form on CUL website on home and internal pages of 200k referrals on catalog.?

We should create a matomo event on catalog search btn in home and internal pages to really see how much catalog search from cul is used.
